[package]
name = "sanctum-token-lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
solana-program = { workspace = true }
solana-readonly-account = { workspace = true }
spl-token-2022 = { workspace = true }
