[package]
name = "sanctum-associated-token-lib"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = { workspace = true }
solana-readonly-account = { workspace = true }
spl-associated-token-account = { workspace = true }
